/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package expression_evaluator;

public class App {
    public static void main(String[] args) {
        new Printer().printSomething();
    }
}
